{% set name = "doi2bib" %}
{% set version = "0.4.0" %}
{% set sha256 = "272458eb88a34ab0fd4c69c6a4f2698496ccd9791d827f52b6c2b3ae6a3a221c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # TODO: use sources from PyPI. See https://github.com/bibcure/doi2bib/issues/7
  # https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/bibcure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bibtexparser
    - future
    - requests

test:
  imports:
    - doi2bib
  commands:
    - doi2bib --help
    - doi2bib 10.1038/nature24270

about:
  home: https://doi2bib.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: get the bibtex string given a doi
  doc_url: https://doi2bib.readthedocs.io
  dev_url: https://github.com/bibcure/doi2bib
